# Generated by Django 6.0.6 on 2026-06-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('vibration', 'Vibration')], max_length=20, unique=True)),
                ('warning_limit', models.FloatField()),
                ('critical_multiplier', models.FloatField(default=1.2)),
                ('unit', models.CharField(default='', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
