# Generated by Django 6.0.6 on 2026-06-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_type', models.CharField(max_length=50)),
                ('calculated_average', models.FloatField()),
                ('critical_limit', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_logs', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Warning', 'Warning'), ('Critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='buildings.building')),
                ('threshold_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.thresholdlog')),
            ],
        ),
    ]
